function [ Track ] = FSAELincoln2013( )
%FSAEWest2011 constructs a track based on the 2011 FSAE West competition
%track.
%   The defined track matches the race line data generated by the operator
%   of www.fsaesim.com.

% Defines section data, one straight section folloed by several curved
% sections.

SectionMatrix = [
    2321,0;
    873,1820;
    760,369;
    1215,0;
    277,678;
    134,0;
    309,441;
    352,415;
    749,734;
    2046,735;
    779,0;
    825,582;
    278,0;
    707,406;
    666,864;
    2445,0;
    847,351;
    524,460;
    1589,0;
    1490,605;
    587,818;
    658,757;
    1078,1004;
    1580,1096;
    965,0;
    691,819;
    361,0;
    1097,522;
    582,0;
    433,1135;
    584,968;
    493,518;
    538,940;
    440,300;
    400,600;
    2544,0;
    924,347;
    1185,615;
    1055,837;
    667,1890;
    697,1189;
    399,0;
    440,324;
    858,841;
    557,720;
    574,873;
    390,1098;
    2250,0;
    843,988;
    930,825;
    435,0;
    698,971;
    400,847;
    200,0;
    301,798;
    466,662;
    454,548;
    891,611;
    ];


N = length(SectionMatrix);

% Builds array of TrackSection objects
for i=1:N
    if SectionMatrix(i,2)
        Length = SectionMatrix(i,1);
        Radius = SectionMatrix(i,2);
        TS = TrackSection(Length,Radius,i);
        TSArray(i) = TS;
    else
        Length = SectionMatrix(i,1);
        TS = TrackSection(Length,0,i);
        TSArray(i) = TS;
    end
end

% Calls TestTrack Constructor
Track = TestTrack(TSArray);


end

